application: chenzhuost
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /index
  script: jane.application

- url: /ask/.*
  script: jane.application

- url: /list/.*
  script: jane.application

- url: /manage
  script: manage.application

- url: /manage/.*
  script: manage.application

- url: /view?.*
  script: view.application



- url: /.*
  script: jane.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest