application: western-octagon-780
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /index
  script: jane.application

- url: /ask/.*
  script: jane.application

- url: /.*
  script: jane.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest